name: C/C++ CI

on:
  push:
    branches: [ master ]
  release:
    types: [published]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: update
      run: sudo apt-get update
    - name: install1
      run: sudo apt-get install gcc-arm-none-eabi
    - name: install2
      run: sudo apt-get install make
    - name: make
      run: make
    - name: Prepare artifact
      run: |
        mkdir -p ./artifact/firmware
        cp -rf $(find ./build -type f -name "*.bin") ./artifact/firmware/
    - name: Deliver firmware
      uses: actions/upload-artifact@v2
      with:
        name: CLtest
        path: ./build
          
    - name: Upload release asset
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./artifact/firmware/*
        tag: ${{ github.ref }}
        file_glob: true
